# Generated by Django 4.2.7 on 2023-11-04 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_conteudo_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 11, 35, 8, 949965, tzinfo=datetime.timezone.utc)),
        ),
    ]
