# Generated by Django 4.2.7 on 2023-11-04 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 13, 2, 51, 661185, tzinfo=datetime.timezone.utc)),
        ),
    ]
